# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

parameters:
-name:seedsecrets
  displayName: 'Seed secrets'
  type: boolean 
  default: false

-name:deployToECS
  displayName:'Deploy to ECS after build'
  type: boolean
  default: false

pool:
name:'ubuntu-latest'

variables:
  group: 'my-variable-group'
  
Stages:
-stage: BuildAndTaskDefinition
displayName: 'Build and Task Definition'
dependsOn: []
condition: ne('${{ parameters.seedsecrets }}', true)
jobs:
- job: BuildAndTaskDefinition 
displayName: 'Build and push'
steps:
-checkout: self
- script: echo Hello, world!
sudo yum install -y runc crun
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
